name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3

    - name: Run TestNG tests
      run: ./gradlew test
      env:
        SPRING_PROFILES_ACTIVE: test
      
    - name: Publish TestNG Results
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: TestNG Tests
        path: build/reports/tests/test/TEST-*.xml
        reporter: java-junit
        
    - name: Build application
      run: ./gradlew build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: build-artifacts
        path: build/libs/*.jar
        
    - name: Upload test reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-reports
        path: build/reports/tests/